// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tornois.Infrastructure.Data;

#nullable disable

namespace Tornois.Infrastructure.Data.Migrations
{
    [DbContext(typeof(TornoisDbContext))]
    [Migration("20260407192323_InitialPostgresSchema")]
    partial class InitialPostgresSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tornois.Infrastructure.Data.AdminUserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at_utc");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("role");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("p_k_admin_user");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("i_x_admin_user_user_name");

                    b.ToTable("admin_user", "admin");
                });

            modelBuilder.Entity("Tornois.Infrastructure.Data.BroadcasterEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("country");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("WebsiteUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("website_url");

                    b.HasKey("Id")
                        .HasName("p_k_broadcaster");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("i_x_broadcaster_name");

                    b.ToTable("broadcaster", "broadcast");
                });

            modelBuilder.Entity("Tornois.Infrastructure.Data.ChangeLogEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("action");

                    b.Property<int?>("AdminUserId")
                        .HasColumnType("integer")
                        .HasColumnName("admin_user_id");

                    b.Property<string>("AfterJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("after_json");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("before_json");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("entity_name");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("summary");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("p_k_change_log");

                    b.HasIndex("AdminUserId")
                        .HasDatabaseName("i_x_change_log_admin_user_id");

                    b.ToTable("change_log", "admin");
                });

            modelBuilder.Entity("Tornois.Infrastructure.Data.CompetitionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("country");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("external_id");

                    b.Property<string>("ExternalSource")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("external_source");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("format");

                    b.Property<bool>("IsCup")
                        .HasColumnType("boolean")
                        .HasColumnName("is_cup");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<int>("SportId")
                        .HasColumnType("integer")
                        .HasColumnName("sport_id");

                    b.HasKey("Id")
                        .HasName("p_k_competition");

                    b.HasIndex("SportId", "Name")
                        .IsUnique()
                        .HasDatabaseName("i_x_competition_sport_id_name");

                    b.ToTable("competition", "sports");
                });

            modelBuilder.Entity("Tornois.Infrastructure.Data.IndividualRankingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("category");

                    b.Property<int>("CompetitionId")
                        .HasColumnType("integer")
                        .HasColumnName("competition_id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("label");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer")
                        .HasColumnName("season_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("p_k_individual_ranking");

                    b.HasIndex("SeasonId")
                        .HasDatabaseName("i_x_individual_ranking_season_id");

                    b.HasIndex("CompetitionId", "SeasonId", "Category", "Label")
                        .IsUnique()
                        .HasDatabaseName("i_x_individual_ranking_competition_id_season_id_category_label");

                    b.ToTable("individual_ranking", "rankings");
                });

            modelBuilder.Entity("Tornois.Infrastructure.Data.MatchBroadcastEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BroadcasterId")
                        .HasColumnType("integer")
                        .HasColumnName("broadcaster_id");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("channel_name");

                    b.Property<int>("MatchId")
                        .HasColumnType("integer")
                        .HasColumnName("match_id");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("region");

                    b.Property<string>("StreamUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("stream_url");

                    b.HasKey("Id")
                        .HasName("p_k_match_broadcast");

                    b.HasIndex("BroadcasterId")
                        .HasDatabaseName("i_x_match_broadcast_broadcaster_id");

                    b.HasIndex("MatchId")
                        .HasDatabaseName("i_x_match_broadcast_match_id");

                    b.ToTable("match_broadcast", "broadcast");
                });

            modelBuilder.Entity("Tornois.Infrastructure.Data.MatchEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AwayScore")
                        .HasColumnType("integer")
                        .HasColumnName("away_score");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("integer")
                        .HasColumnName("away_team_id");

                    b.Property<int>("CompetitionId")
                        .HasColumnType("integer")
                        .HasColumnName("competition_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("HomeScore")
                        .HasColumnType("integer")
                        .HasColumnName("home_score");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("integer")
                        .HasColumnName("home_team_id");

                    b.Property<DateTimeOffset>("KickoffUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("kickoff_utc");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer")
                        .HasColumnName("season_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("source");

                    b.Property<int>("SportId")
                        .HasColumnType("integer")
                        .HasColumnName("sport_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("venue");

                    b.HasKey("Id")
                        .HasName("p_k_match");

                    b.HasIndex("AwayTeamId")
                        .HasDatabaseName("i_x_match_away_team_id");

                    b.HasIndex("HomeTeamId")
                        .HasDatabaseName("i_x_match_home_team_id");

                    b.HasIndex("SeasonId")
                        .HasDatabaseName("i_x_match_season_id");

                    b.HasIndex("SportId")
                        .HasDatabaseName("i_x_match_sport_id");

                    b.HasIndex("CompetitionId", "SeasonId", "KickoffUtc")
                        .HasDatabaseName("i_x_match_competition_id_season_id_kickoff_utc");

                    b.ToTable("match", "matches");
                });

            modelBuilder.Entity("Tornois.Infrastructure.Data.MatchEventEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("MatchId")
                        .HasColumnType("integer")
                        .HasColumnName("match_id");

                    b.Property<int>("Minute")
                        .HasColumnType("integer")
                        .HasColumnName("minute");

                    b.Property<int?>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subject");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("p_k_match_event");

                    b.HasIndex("MatchId")
                        .HasDatabaseName("i_x_match_event_match_id");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("i_x_match_event_person_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("i_x_match_event_team_id");

                    b.ToTable("match_event", "matches");
                });

            modelBuilder.Entity("Tornois.Infrastructure.Data.PersonEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("bio");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("full_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nationality");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("photo_url");

                    b.Property<string>("PrimaryRole")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("primary_role");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("p_k_person");

                    b.HasIndex("FullName")
                        .HasDatabaseName("i_x_person_full_name");

                    b.ToTable("person", "people");
                });

            modelBuilder.Entity("Tornois.Infrastructure.Data.PersonRankingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<int>("RankingId")
                        .HasColumnType("integer")
                        .HasColumnName("ranking_id");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.Property<int>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("p_k_person_ranking");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("i_x_person_ranking_person_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("i_x_person_ranking_team_id");

                    b.HasIndex("RankingId", "PersonId")
                        .IsUnique()
                        .HasDatabaseName("i_x_person_ranking_ranking_id_person_id");

                    b.ToTable("person_ranking", "rankings");
                });

            modelBuilder.Entity("Tornois.Infrastructure.Data.PlayerStatEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("category");

                    b.Property<int>("MatchId")
                        .HasColumnType("integer")
                        .HasColumnName("match_id");

                    b.Property<decimal>("MetricValue")
                        .HasColumnType("numeric")
                        .HasColumnName("metric_value");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at_utc");

                    b.Property<string>("StatPayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("stat_payload_json");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.HasKey("Id")
                        .HasName("p_k_player_stat");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("i_x_player_stat_person_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("i_x_player_stat_team_id");

                    b.HasIndex("MatchId", "PersonId", "Category")
                        .HasDatabaseName("i_x_player_stat_match_id_person_id_category");

                    b.ToTable("player_stat", "stats");
                });

            modelBuilder.Entity("Tornois.Infrastructure.Data.SeasonEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompetitionId")
                        .HasColumnType("integer")
                        .HasColumnName("competition_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_current");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name");

                    b.Property<int>("YearEnd")
                        .HasColumnType("integer")
                        .HasColumnName("year_end");

                    b.Property<int>("YearStart")
                        .HasColumnType("integer")
                        .HasColumnName("year_start");

                    b.HasKey("Id")
                        .HasName("p_k_season");

                    b.HasIndex("CompetitionId", "Name")
                        .IsUnique()
                        .HasDatabaseName("i_x_season_competition_id_name");

                    b.ToTable("season", "sports");
                });

            modelBuilder.Entity("Tornois.Infrastructure.Data.SportEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsOlympic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_olympic");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("p_k_sport");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("i_x_sport_slug");

                    b.ToTable("sport", "sports");
                });

            modelBuilder.Entity("Tornois.Infrastructure.Data.StandingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompetitionId")
                        .HasColumnType("integer")
                        .HasColumnName("competition_id");

                    b.Property<int>("Drawn")
                        .HasColumnType("integer")
                        .HasColumnName("drawn");

                    b.Property<int>("GoalsAgainst")
                        .HasColumnType("integer")
                        .HasColumnName("goals_against");

                    b.Property<int>("GoalsFor")
                        .HasColumnType("integer")
                        .HasColumnName("goals_for");

                    b.Property<int>("Lost")
                        .HasColumnType("integer")
                        .HasColumnName("lost");

                    b.Property<int>("Played")
                        .HasColumnType("integer")
                        .HasColumnName("played");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer")
                        .HasColumnName("season_id");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("Won")
                        .HasColumnType("integer")
                        .HasColumnName("won");

                    b.HasKey("Id")
                        .HasName("p_k_standing");

                    b.HasIndex("SeasonId")
                        .HasDatabaseName("i_x_standing_season_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("i_x_standing_team_id");

                    b.HasIndex("CompetitionId", "SeasonId", "TeamId")
                        .IsUnique()
                        .HasDatabaseName("i_x_standing_competition_id_season_id_team_id");

                    b.ToTable("standing", "rankings");
                });

            modelBuilder.Entity("Tornois.Infrastructure.Data.TeamEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BadgeUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("badge_url");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("country");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("Founded")
                        .HasColumnType("integer")
                        .HasColumnName("founded");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("name");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("short_name");

                    b.Property<int>("SportId")
                        .HasColumnType("integer")
                        .HasColumnName("sport_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("venue");

                    b.HasKey("Id")
                        .HasName("p_k_team");

                    b.HasIndex("SportId", "Name")
                        .IsUnique()
                        .HasDatabaseName("i_x_team_sport_id_name");

                    b.ToTable("team", "teams");
                });

            modelBuilder.Entity("Tornois.Infrastructure.Data.TeamMemberEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("JoinedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at_utc");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<int?>("ShirtNumber")
                        .HasColumnType("integer")
                        .HasColumnName("shirt_number");

                    b.Property<string>("SquadRole")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("squad_role");

                    b.Property<int>("TeamSeasonId")
                        .HasColumnType("integer")
                        .HasColumnName("team_season_id");

                    b.HasKey("Id")
                        .HasName("p_k_team_member");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("i_x_team_member_person_id");

                    b.HasIndex("TeamSeasonId", "PersonId")
                        .IsUnique()
                        .HasDatabaseName("i_x_team_member_team_season_id_person_id");

                    b.ToTable("team_member", "teams");
                });

            modelBuilder.Entity("Tornois.Infrastructure.Data.TeamSeasonEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CoachName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("coach_name");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer")
                        .HasColumnName("season_id");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.HasKey("Id")
                        .HasName("p_k_team_season");

                    b.HasIndex("SeasonId")
                        .HasDatabaseName("i_x_team_season_season_id");

                    b.HasIndex("TeamId", "SeasonId")
                        .IsUnique()
                        .HasDatabaseName("i_x_team_season_team_id_season_id");

                    b.ToTable("team_season", "teams");
                });

            modelBuilder.Entity("Tornois.Infrastructure.Data.ChangeLogEntity", b =>
                {
                    b.HasOne("Tornois.Infrastructure.Data.AdminUserEntity", null)
                        .WithMany()
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_change_log_admin_user_admin_user_id");
                });

            modelBuilder.Entity("Tornois.Infrastructure.Data.CompetitionEntity", b =>
                {
                    b.HasOne("Tornois.Infrastructure.Data.SportEntity", null)
                        .WithMany()
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_competition_sport_sport_id");
                });

            modelBuilder.Entity("Tornois.Infrastructure.Data.IndividualRankingEntity", b =>
                {
                    b.HasOne("Tornois.Infrastructure.Data.CompetitionEntity", null)
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_individual_ranking_competition_competition_id");

                    b.HasOne("Tornois.Infrastructure.Data.SeasonEntity", null)
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_individual_ranking_season_season_id");
                });

            modelBuilder.Entity("Tornois.Infrastructure.Data.MatchBroadcastEntity", b =>
                {
                    b.HasOne("Tornois.Infrastructure.Data.BroadcasterEntity", null)
                        .WithMany()
                        .HasForeignKey("BroadcasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_match_broadcast_broadcaster_broadcaster_id");

                    b.HasOne("Tornois.Infrastructure.Data.MatchEntity", null)
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_match_broadcast_match_match_id");
                });

            modelBuilder.Entity("Tornois.Infrastructure.Data.MatchEntity", b =>
                {
                    b.HasOne("Tornois.Infrastructure.Data.TeamEntity", null)
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_match_team_away_team_id");

                    b.HasOne("Tornois.Infrastructure.Data.CompetitionEntity", null)
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_match_competition_competition_id");

                    b.HasOne("Tornois.Infrastructure.Data.TeamEntity", null)
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_match_team_home_team_id");

                    b.HasOne("Tornois.Infrastructure.Data.SeasonEntity", null)
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_match_season_season_id");

                    b.HasOne("Tornois.Infrastructure.Data.SportEntity", null)
                        .WithMany()
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_match_sport_sport_id");
                });

            modelBuilder.Entity("Tornois.Infrastructure.Data.MatchEventEntity", b =>
                {
                    b.HasOne("Tornois.Infrastructure.Data.MatchEntity", null)
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_match_event_match_match_id");

                    b.HasOne("Tornois.Infrastructure.Data.PersonEntity", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_match_event_person_person_id");

                    b.HasOne("Tornois.Infrastructure.Data.TeamEntity", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_match_event_team_team_id");
                });

            modelBuilder.Entity("Tornois.Infrastructure.Data.PersonRankingEntity", b =>
                {
                    b.HasOne("Tornois.Infrastructure.Data.PersonEntity", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_person_ranking_person_person_id");

                    b.HasOne("Tornois.Infrastructure.Data.IndividualRankingEntity", null)
                        .WithMany()
                        .HasForeignKey("RankingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_person_ranking_individual_ranking_ranking_id");

                    b.HasOne("Tornois.Infrastructure.Data.TeamEntity", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_person_ranking_team_team_id");
                });

            modelBuilder.Entity("Tornois.Infrastructure.Data.PlayerStatEntity", b =>
                {
                    b.HasOne("Tornois.Infrastructure.Data.MatchEntity", null)
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_player_stat_match_match_id");

                    b.HasOne("Tornois.Infrastructure.Data.PersonEntity", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_player_stat_person_person_id");

                    b.HasOne("Tornois.Infrastructure.Data.TeamEntity", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_player_stat_team_team_id");
                });

            modelBuilder.Entity("Tornois.Infrastructure.Data.SeasonEntity", b =>
                {
                    b.HasOne("Tornois.Infrastructure.Data.CompetitionEntity", null)
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_season_competition_competition_id");
                });

            modelBuilder.Entity("Tornois.Infrastructure.Data.StandingEntity", b =>
                {
                    b.HasOne("Tornois.Infrastructure.Data.CompetitionEntity", null)
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_standing_competition_competition_id");

                    b.HasOne("Tornois.Infrastructure.Data.SeasonEntity", null)
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_standing_season_season_id");

                    b.HasOne("Tornois.Infrastructure.Data.TeamEntity", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_standing_team_team_id");
                });

            modelBuilder.Entity("Tornois.Infrastructure.Data.TeamEntity", b =>
                {
                    b.HasOne("Tornois.Infrastructure.Data.SportEntity", null)
                        .WithMany()
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_team_sport_sport_id");
                });

            modelBuilder.Entity("Tornois.Infrastructure.Data.TeamMemberEntity", b =>
                {
                    b.HasOne("Tornois.Infrastructure.Data.PersonEntity", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_team_member_person_person_id");

                    b.HasOne("Tornois.Infrastructure.Data.TeamSeasonEntity", null)
                        .WithMany()
                        .HasForeignKey("TeamSeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_team_member_team_season_team_season_id");
                });

            modelBuilder.Entity("Tornois.Infrastructure.Data.TeamSeasonEntity", b =>
                {
                    b.HasOne("Tornois.Infrastructure.Data.SeasonEntity", null)
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_team_season_season_season_id");

                    b.HasOne("Tornois.Infrastructure.Data.TeamEntity", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_team_season_team_team_id");
                });
#pragma warning restore 612, 618
        }
    }
}
